# Generated by Django 3.0 on 2021-08-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='wp2027011.jpg', upload_to='images/'),
        ),
    ]
